USE [master]
GO

/****** Object:  Database [ContrastShopDatabase]    Script Date: 27.05.2023 18:08:09 ******/
CREATE DATABASE [ContrastShopDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContrastShopDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ContrastShopDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContrastShopDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ContrastShopDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContrastShopDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContrastShopDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ContrastShopDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContrastShopDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContrastShopDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ContrastShopDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContrastShopDatabase] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ContrastShopDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ContrastShopDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [ContrastShopDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContrastShopDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContrastShopDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContrastShopDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ContrastShopDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContrastShopDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ContrastShopDatabase] SET QUERY_STORE = ON
GO

ALTER DATABASE [ContrastShopDatabase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ContrastShopDatabase] SET  READ_WRITE 
GO

